apiVersion: v1
kind: PersistentVolume
metadata:
  name: iom-pv-nfs-pv1
  labels:
    type: local
spec:
  storageClassName: iom-nfs-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.76
    path: /mnt/ssd-disk/iom
