kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysqldb-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysqldb-server
  template:
    metadata:
      labels:
        app: mysqldb-server
    spec:
      containers:
        - name: mysqldb-server
          image: fculibao/mysqldb-arm64v8:latest
          volumeMounts:
            - name: mysqldb-pv
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysqldb-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: db-pass
      volumes:
        - name: mysqldb-pv
          persistentVolumeClaim:
            claimName: mysqldb-pvc
