apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqldb-pv
  labels:
    type: local
spec:
  storageClassName: mysqldb-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.76
    path: /mnt/ssd-disk/mysqldb-data
